name: Build API docs
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
permissions:
  contents: read
  id-token: write
  pages: write
concurrency:
  group: pages
  cancel-in-progress: true
jobs:
  build:
    container: alpine:edge
    runs-on: ubuntu-latest
    env:
      INSPIRCD_BRANCHES: insp3 master
      INSPIRCD_TAGS: v3 v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |-
          apk add doxygen git python3 py3-pip tar
          pip3 install --break-system-packages jinja2

      - name: Build API docs
        run: |-
          ./mkapi

      - name: Upload API docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Deploy API docs to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
