name: Check API docs
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    container: alpine:edge
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    env:
      INSPIRCD_BRANCHES: insp3 master
      INSPIRCD_TAGS: v3 v4
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |-
          apk add doxygen git python3 py3-pip
          pip3 install --break-system-packages jinja2

      - name: Build API docs
        run: |-
          ./mkapi
